apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: targeting-service-pdb
  namespace: togglemaster
  labels:
    app: targeting-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: targeting-service
